### ISSUE TITLE
Installing Custom Weapons

### ISSUE THREAD

**Issue by Sidewinder92** [KernCore91/Counter-Strike-1.6-to-Sven-Coop#1]
Hey there KernCore91,

I need your help with installing the CS 1.6 weapons. Really like those scripts, I saw them on a server and thought I could install it on my own server, the issue is - the forums are down. Can you help?

Regards,
Sidewinder92

**Comment by KernCore91** [comment]
You gotta use Google Cache in order to search for the old thread, or use a old backup in webarchive/archive.is, which I made right here: http://archive.is/9LyW6

**Comment by Sidewinder92** [comment]
Hey KernCore91,

thank you so much for that link. However, the download links are broken. Can you please tell which files those downloads consisted of? I will try to create them myself, unless the downloads are still available from a different source.

Regards,
Sidewinder91

**Comment by KernCore91** [comment]
Sorry, here they are: https://www.dropbox.com/s/0qmz1kz00k3xfid/Sven-CS16_2-1.7z?dl=0
https://mega.nz/file/b9FXiCAK#xjjtkdRnO62r6N4MP5ns3lwKQ2y-uNQsTmsWLPr36Y0

**Comment by Sidewinder92** [comment]
Hey KernCore91,

thank you so much for your help. This is an excellent mod. I appreciate it alot.

Regards,
Sidewinder91

**Comment by Sidewinder92** [comment]
Hey KernCore91,

thank you so much for this plugin and your help. This is a great addition to the weapon arsenal of Sven Coop. I like this mod so much.

With greatest regards,
Sidewinder92

**Comment by KernCore91** [comment]
Glad you like it.
